import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#0A0E1A' },
  topBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 20, paddingBottom: 12 },
  pageTitle: { fontSize: 22, fontWeight: '800', color: '#CCD6F6' },
  addBtn: { backgroundColor: '#00D4FF', borderRadius: 8, paddingHorizontal: 16, paddingVertical: 8 },
  addBtnText: { color: '#0A0E1A', fontWeight: '800', fontSize: 14 },
  container: { padding: 20, paddingTop: 0, paddingBottom: 40, gap: 12 },
  emptyBox: { alignItems: 'center', marginTop: 80, gap: 12 },
  emptyIcon: { fontSize: 48 },
  emptyText: { color: '#4A5568', fontSize: 15 },
  card: { backgroundColor: '#131929', borderRadius: 14, padding: 16 },
  cardRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  dot: { width: 10, height: 10, borderRadius: 5 },
  cardName: { color: '#CCD6F6', fontSize: 15, fontWeight: '700' },
  cardSub: { color: '#8892B0', fontSize: 13, marginTop: 2 },
  cardActions: { flexDirection: 'row', gap: 8 },
  editBtn: { backgroundColor: '#1E2A3A', borderRadius: 6, paddingHorizontal: 12, paddingVertical: 6 },
  editBtnText: { color: '#00D4FF', fontSize: 13, fontWeight: '600' },
  deleteBtn: { backgroundColor: '#3A1020', borderRadius: 6, paddingHorizontal: 12, paddingVertical: 6 },
  deleteBtnText: { color: '#FF4D6D', fontSize: 13, fontWeight: '600' },
  cardMeta: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: '#1E2A3A' },
  metaText: { color: '#8892B0', fontSize: 12 },
  // Modal
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'flex-end' },
  modalCard: { backgroundColor: '#131929', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 28, gap: 12 },
  modalTitle: { fontSize: 20, fontWeight: '800', color: '#CCD6F6', marginBottom: 4 },
  label: { color: '#8892B0', fontSize: 13, fontWeight: '600' },
  input: { backgroundColor: '#0A0E1A', borderRadius: 10, padding: 14, color: '#CCD6F6', fontSize: 15, borderWidth: 1, borderColor: '#1E2A3A' },
  toggleRow: { flexDirection: 'row', gap: 10 },
  toggleBtn: { flex: 1, borderRadius: 8, padding: 12, alignItems: 'center', backgroundColor: '#0A0E1A', borderWidth: 1, borderColor: '#1E2A3A' },
  toggleActive: { backgroundColor: '#0D3A2E', borderColor: '#00D4AA' },
  toggleInactive: { backgroundColor: '#3A0D0D', borderColor: '#FF4D6D' },
  toggleText: { color: '#8892B0', fontWeight: '700' },
  toggleTextActive: { color: '#00D4AA' },
  toggleTextInactive: { color: '#FF4D6D' },
  modalActions: { flexDirection: 'row', gap: 12, marginTop: 8 },
  cancelBtn: { flex: 1, borderWidth: 1, borderColor: '#1E2A3A', borderRadius: 10, padding: 14, alignItems: 'center' },
  cancelText: { color: '#8892B0', fontWeight: '700' },
  saveBtn: { flex: 1, backgroundColor: '#00D4FF', borderRadius: 10, padding: 14, alignItems: 'center' },
  saveBtnText: { color: '#0A0E1A', fontWeight: '800', fontSize: 15 },
});